#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J ds-openmp
#SBATCH -o ds-openmp.stdout
#SBATCH -n 16         
#SBATCH -p normal
#SBATCH -t 00:10:00     


export OMP_NUM_THREADS= 4
./openmpDS -n 10000 -s opds.txt
